"""Upload EsquelProp properties scraped from esquelprop.com to Google Sheet."""
import json, os, sys
from dotenv import load_dotenv
load_dotenv("/Users/msg1234/Desktop/PropBot/RealStateBotWA/.env")

import gspread
from google.oauth2.service_account import Credentials

# --- Auth ---
creds_json = os.environ["GOOGLE_CREDENTIALS_JSON"]
sheet_id = os.environ["GOOGLE_SHEET_ID"]
scopes = ["https://www.googleapis.com/auth/spreadsheets"]
creds_dict = json.loads(creds_json)
creds = Credentials.from_service_account_info(creds_dict, scopes=scopes)
gc = gspread.authorize(creds)

# --- Properties scraped from esquelprop.com ---
properties = [
    {
        "id": "EP001",
        "titulo": "Casa 3 ambientes Yrigoyen y Don Bosco",
        "precio_usd": 90000,
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Casa",
        "ambientes": 3,
        "dormitorios": 2,
        "banos": 1,
        "mt2_cubiertos": "",
        "mt2_totales": "",
        "barrio": "Yrigoyen y Don Bosco, Esquel",
        "direccion": "Yrigoyen y Don Bosco, Esquel",
        "cochera": "No",
        "balcon": "No",
        "patio_delantero": "No",
        "patio_trasero": "No",
        "terraza": "No",
        "jardin": "Si",
        "pileta": "No",
        "quincho": "No",
        "descripcion": "Dos casas independientes en mismo terreno, construcción tradicional, no comparten paredes. Estar-comedor, cocina, patio libre. Se venden juntas o separadas a USD 90.000 cada una.",
        "fotos_url": "https://esquelprop.com/propiedad/casa-3-ambientes-yrigoyen-y-don-bosco/",
    },
    {
        "id": "EP002",
        "titulo": "Casa 2 dormitorios Ruta 259",
        "precio_usd": "Consultar",
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Casa",
        "ambientes": "",
        "dormitorios": 2,
        "banos": 2,
        "suite": "Si",
        "mt2_cubiertos": 100,
        "mt2_totales": 900,
        "barrio": "Ruta 259, Esquel",
        "direccion": "Ruta 259 km 3, Esquel",
        "cochera": "Si",
        "balcon": "No",
        "patio_delantero": "No",
        "patio_trasero": "No",
        "terraza": "No",
        "jardin": "Si",
        "pileta": "No",
        "quincho": "No",
        "calefaccion": "Central",
        "descripcion": "Casa con calefacción central, cochera cubierta, gran espacio libre exterior, paisaje sin igual. Living-comedor, cocina-comedor, lavadero. Lote de 900 m².",
        "fotos_url": "https://esquelprop.com/propiedad/casa-2-dormitorios-ruta-259/",
    },
    {
        "id": "EP003",
        "titulo": "Casa en venta en Bo. Baden, Esquel",
        "precio_usd": 85000,
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Casa",
        "ambientes": "",
        "dormitorios": 3,
        "banos": 1,
        "mt2_cubiertos": "",
        "mt2_totales": "",
        "barrio": "Barrio Baden, Esquel",
        "direccion": "Barrio Baden, Esquel",
        "cochera": "",
        "balcon": "No",
        "patio_delantero": "Si",
        "patio_trasero": "No",
        "terraza": "No",
        "jardin": "Si",
        "pileta": "No",
        "quincho": "No",
        "descripcion": "Casa de dos plantas en mampostería con escritura inmediata. Dormitorios grandes en planta alta, ambientes luminosos. Living comedor, cocina comedor, lavadero.",
        "fotos_url": "https://esquelprop.com/propiedad/casa-en-venta-en-bo-baden-esquel/",
    },
    {
        "id": "EP004",
        "titulo": "Casa 6 ambientes Esquel",
        "precio_usd": 85000,
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Casa",
        "ambientes": 6,
        "dormitorios": 5,
        "banos": 2,
        "mt2_cubiertos": 120,
        "mt2_totales": "",
        "barrio": "Pasaje Mansilla, Esquel",
        "direccion": "Pasaje Mansilla, Esquel",
        "cochera": "",
        "balcon": "No",
        "patio_delantero": "No",
        "patio_trasero": "No",
        "terraza": "No",
        "jardin": "Si",
        "pileta": "No",
        "quincho": "No",
        "descripcion": "Estética patagónica en piedra y madera. PB: 2 cuartos, cocina, comedor, living con fogón, toilette. PA: 3 dormitorios + baño. Muy cerca del centro. Jardín al frente con rejas.",
        "fotos_url": "https://esquelprop.com/propiedad/casa-6-ambientes-esquel/",
    },
    {
        "id": "EP005",
        "titulo": "Casa 3 dormitorios Esquel",
        "precio_usd": 55000,
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Casa",
        "ambientes": "",
        "dormitorios": 3,
        "banos": 2,
        "mt2_cubiertos": 140,
        "mt2_totales": "",
        "barrio": "Barrio 25 de Mayo, Esquel",
        "direccion": "25 de Mayo y O'Higgins, Esquel",
        "cochera": "Si",
        "balcon": "No",
        "patio_delantero": "No",
        "patio_trasero": "Si",
        "terraza": "No",
        "jardin": "Si",
        "pileta": "No",
        "quincho": "No",
        "descripcion": "PB: cocina, comedor, varios ambientes, baño. PA: 3 dormitorios + baño. Garage con portón. Patio cubierto con fogón y frutales. Requiere algunos arreglos.",
        "fotos_url": "https://esquelprop.com/propiedad/casa-3-domitorios-esquel/",
    },
    {
        "id": "EP006",
        "titulo": "Gran casa en Villa Ayelén, Esquel",
        "precio_usd": "Consultar",
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Casa",
        "ambientes": "",
        "dormitorios": 3,
        "banos": 2,
        "mt2_cubiertos": "",
        "mt2_totales": 800,
        "barrio": "Villa Ayelén, Esquel",
        "direccion": "Villa Ayelén, Esquel",
        "cochera": "Si",
        "balcon": "No",
        "patio_delantero": "No",
        "patio_trasero": "Si",
        "terraza": "No",
        "jardin": "Si",
        "pileta": "No",
        "quincho": "Si",
        "descripcion": "Importante residencia de 2 plantas. Living comedor con hogar, cocina equipada, dormitorios con placards. Incluye departamento independiente de 2 ambientes. Gran garage. Fondo parquizado. Zona tranquila y residencial.",
        "fotos_url": "https://esquelprop.com/propiedad/gran-casa-en-villa-ayelen-esquel/",
    },
    {
        "id": "EP007",
        "titulo": "4 casas a construir en Laderas del Sol",
        "precio_usd": "Consultar",
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Casa",
        "ambientes": "",
        "dormitorios": 2,
        "banos": 1,
        "mt2_cubiertos": 60,
        "mt2_totales": 65,
        "barrio": "Laderas del Sol, Esquel",
        "direccion": "Laderas del Sol, Esquel",
        "cochera": "Si",
        "balcon": "No",
        "patio_delantero": "No",
        "patio_trasero": "Si",
        "terraza": "No",
        "jardin": "No",
        "pileta": "No",
        "quincho": "No",
        "descripcion": "Desarrollo exclusivo de 4 unidades residenciales (2 de 60m² y 2 de 65m²). Cocina-comedor equipada, 2 dormitorios con placares, baño completo, entrada para vehículo, patio. Financiación: 55% anticipo + 10 cuotas en USD.",
        "fotos_url": "https://esquelprop.com/propiedad/4-casas-a-construir-en-laderas-del-sol/",
    },
    {
        "id": "EP008",
        "titulo": "3 departamentos en un mismo lote",
        "precio_usd": "Consultar",
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Departamento",
        "ambientes": "",
        "dormitorios": 4,
        "banos": 3,
        "mt2_cubiertos": "",
        "mt2_totales": "",
        "barrio": "Juan Manuel de Rosas, Esquel",
        "direccion": "Juan Manuel de Rosas 1700, Esquel",
        "cochera": "",
        "balcon": "No",
        "patio_delantero": "No",
        "patio_trasero": "Si",
        "terraza": "No",
        "jardin": "Si",
        "pileta": "No",
        "quincho": "No",
        "descripcion": "3 unidades: depto frente (cocina-comedor + 2 dorm + baño), dúplex (cocina-comedor + baño PB, dormitorio PA), depto fondo (cocina-comedor + habitación + baño). Amplio fondo. Ideal inversión/renta.",
        "fotos_url": "https://esquelprop.com/propiedad/3-departamentos-en-un-mismo-lote/",
    },
    {
        "id": "EP009",
        "titulo": "Complejo Habitacional 8 unidades",
        "precio_usd": "Consultar",
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Complejo",
        "ambientes": "",
        "dormitorios": 3,
        "banos": 2,
        "mt2_cubiertos": 370,
        "mt2_totales": 648,
        "barrio": "Mitre, Esquel",
        "direccion": "Mitre 850, Esquel",
        "cochera": "Si",
        "balcon": "No",
        "patio_delantero": "No",
        "patio_trasero": "No",
        "terraza": "No",
        "jardin": "Si",
        "pileta": "No",
        "quincho": "No",
        "descripcion": "8 unidades de 1, 2 y 3 ambientes. Garaje y parque interno. Servicios de gas y electricidad. Entre Av. Alvear y Sáenz Peña. Oportunidad de inversión.",
        "fotos_url": "https://esquelprop.com/propiedad/complejo-habitacional/",
    },
    {
        "id": "EP010",
        "titulo": "Alquiler local + vivienda - 25 de Mayo y Almafuerte",
        "precio_usd": "Consultar",
        "tipo_operacion": "Alquiler",
        "tipo_propiedad": "Local/Vivienda",
        "ambientes": "",
        "dormitorios": 4,
        "banos": 3,
        "mt2_cubiertos": 350,
        "mt2_totales": "",
        "barrio": "25 de Mayo y Almafuerte, Esquel",
        "direccion": "25 de Mayo y Almafuerte, Esquel",
        "cochera": "",
        "balcon": "No",
        "patio_delantero": "No",
        "patio_trasero": "No",
        "terraza": "No",
        "jardin": "No",
        "pileta": "No",
        "quincho": "No",
        "calefaccion": "Losa radiante",
        "descripcion": "PB: local comercial ~170 m². PA: vivienda/oficinas ~180 m² con 4 dormitorios, living, cocina-comedor, fogón/parrilla. Calefacción losa radiante. Se alquilan juntas o separadas.",
        "fotos_url": "https://esquelprop.com/propiedad/alquiler-juntas-o-separadas/",
    },
    {
        "id": "EP011",
        "titulo": "Galpón multipropósito en Esquel",
        "precio_usd": "Consultar",
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Galpón",
        "ambientes": "",
        "dormitorios": "",
        "banos": 2,
        "mt2_cubiertos": 625,
        "mt2_totales": 1250,
        "barrio": "Volta, Esquel",
        "direccion": "Volta 300, Esquel",
        "cochera": "Si",
        "balcon": "No",
        "patio_delantero": "No",
        "patio_trasero": "No",
        "terraza": "No",
        "jardin": "No",
        "pileta": "No",
        "quincho": "No",
        "descripcion": "Salón de exposición, dos naves con portones para camiones, oficinas administrativas, 625 m² espacio maniobra. A media cuadra de avenida principal, 300m del centro.",
        "fotos_url": "https://esquelprop.com/propiedad/galpon-multiproposito-en-venta-en-esquel-ubicacion-estrategica/",
    },
    {
        "id": "EP012",
        "titulo": "Lote de 1.500 m² Villa Ayelén",
        "precio_usd": 40000,
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Lote",
        "ambientes": "",
        "dormitorios": "",
        "banos": "",
        "mt2_cubiertos": "",
        "mt2_totales": 1500,
        "barrio": "Villa Ayelén, Esquel",
        "direccion": "Calle Amancay, Villa Ayelén, Esquel",
        "cochera": "",
        "descripcion": "Rodeado de vegetación y pinares, trabajos de suelos realizados, servicios en la puerta. Ideal casa de dos niveles.",
        "fotos_url": "https://esquelprop.com/propiedad/lote-de-1-500-mts2-villa-ayelen/",
    },
    {
        "id": "EP013",
        "titulo": "Terreno de 800 m² Villa Ayelén",
        "precio_usd": 45000,
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Terreno",
        "ambientes": "",
        "dormitorios": "",
        "banos": "",
        "mt2_cubiertos": "",
        "mt2_totales": 800,
        "barrio": "Villa Ayelén, Esquel",
        "direccion": "Villa Ayelén, Esquel",
        "cochera": "",
        "descripcion": "Terreno de 20x40. Luz subterránea instalada, ubicación privilegiada.",
        "fotos_url": "https://esquelprop.com/propiedad/terreno-de-800-mts2-villa-ayelen/",
    },
    {
        "id": "EP014",
        "titulo": "Lote de 2.000 m² Esquel",
        "precio_usd": 29000,
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Lote",
        "ambientes": "",
        "dormitorios": "",
        "banos": "",
        "mt2_cubiertos": "",
        "mt2_totales": 2000,
        "barrio": "Villa Ayelén, Esquel",
        "direccion": "Villa Ayelén, Esquel",
        "cochera": "",
        "descripcion": "En altos con 2 terrazas sobre dos calles. Planos presentados para mensura. Zona residencial a 5 minutos del centro.",
        "fotos_url": "https://esquelprop.com/propiedad/lote-de-2000-mts2-esquel/",
    },
    {
        "id": "EP015",
        "titulo": "Lote 375 m² Avellaneda y Pioneros",
        "precio_usd": 50000,
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Lote",
        "ambientes": "",
        "dormitorios": "",
        "banos": "",
        "mt2_cubiertos": "",
        "mt2_totales": 375,
        "barrio": "Avellaneda y Pioneros, Esquel",
        "direccion": "Avellaneda y Pioneros, Esquel",
        "cochera": "",
        "descripcion": "Terreno plano en esquina con vistas panorámicas. Luz, agua y gas natural. Escritura registrada. Apto múltiples cabañas/dúplex. 30x12,50m.",
        "fotos_url": "https://esquelprop.com/propiedad/lote-300-mts2-avellaneda-y-pioneros/",
    },
    {
        "id": "EP016",
        "titulo": "5 Lotes en Av. Ameghino y Volta, Esquel",
        "precio_usd": "Consultar",
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Lote",
        "ambientes": "",
        "dormitorios": "",
        "banos": "",
        "mt2_cubiertos": "",
        "mt2_totales": "",
        "barrio": "Av. Ameghino y Volta, Esquel",
        "direccion": "Av. Ameghino y Volta, Esquel",
        "cochera": "",
        "descripcion": "5 lotes en esquina estratégica, alta visibilidad y tránsito. Juntos o individuales. Ideales desarrollo turístico, comercial o residencial.",
        "fotos_url": "https://esquelprop.com/propiedad/5-lotes-esquel/",
    },
    {
        "id": "EP017",
        "titulo": "Lote 800 m² Loteo Los Coihues",
        "precio_usd": "Consultar",
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Lote",
        "ambientes": "",
        "dormitorios": "",
        "banos": "",
        "mt2_cubiertos": "",
        "mt2_totales": 800,
        "barrio": "Barrio Coihues, Esquel",
        "direccion": "Barrio Coihues, entrada a Esquel",
        "cochera": "",
        "descripcion": "En el valle rodeado de montañas. Luz, agua y calles consolidadas.",
        "fotos_url": "https://esquelprop.com/propiedad/lote-800-mts2-en-loteo-los-coihues-esquel/",
    },
    {
        "id": "EP018",
        "titulo": "Fracción de 3.900 m² Villa Ayelén",
        "precio_usd": 54000,
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Terreno",
        "ambientes": "",
        "dormitorios": "",
        "banos": "",
        "mt2_cubiertos": "",
        "mt2_totales": 3900,
        "barrio": "Villa Ayelén, Esquel",
        "direccion": "Villa Ayelén, Esquel",
        "cochera": "",
        "descripcion": "Terreno con pendiente, forma triangular con tres terrazas y vistas panorámicas. Frente a calle principal. Agua, energía disponibles. Listo para escriturar. A 5 min del centro.",
        "fotos_url": "https://esquelprop.com/propiedad/fraccion-4-900-mts2-esquel/",
    },
    {
        "id": "EP019",
        "titulo": "Lote 870 m² en esquina, Trevelin",
        "precio_usd": 49000,
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Lote",
        "ambientes": "",
        "dormitorios": "",
        "banos": "",
        "mt2_cubiertos": "",
        "mt2_totales": 870,
        "barrio": "Loteo Altavista, Trevelin",
        "direccion": "Loteo Altavista, Trevelin",
        "cochera": "",
        "descripcion": "Lote en esquina, mayor amplitud visual y acceso. Con escritura. Trevelin 'El Jardín de la Provincia'.",
        "fotos_url": "https://esquelprop.com/propiedad/lote-870-mts2-en-esquina/",
    },
    {
        "id": "EP020",
        "titulo": "Lotes en Loteo Nueva Gales, Trevelin",
        "precio_usd": "Consultar",
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Lote",
        "ambientes": "",
        "dormitorios": "",
        "banos": "",
        "mt2_cubiertos": "",
        "mt2_totales": 800,
        "barrio": "Av. San Martín, Trevelin",
        "direccion": "Av. San Martín (zona 5 Esquinas), Trevelin",
        "cochera": "",
        "descripcion": "Servicios en el frente (luz, agua, gas). Alto crecimiento urbano. Contado o financiación. ~800 m² cada lote.",
        "fotos_url": "https://esquelprop.com/propiedad/lotes-en-venta-en-loteo-nueva-gales-trevelin/",
    },
    {
        "id": "EP021",
        "titulo": "Fracción de 5.000 m² entrada a Trevelin",
        "precio_usd": "Consultar",
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Terreno",
        "ambientes": "",
        "dormitorios": "",
        "banos": "",
        "mt2_cubiertos": "",
        "mt2_totales": 5000,
        "barrio": "Entrada a Trevelin",
        "direccion": "Ruta 259, entrada a Trevelin",
        "cochera": "",
        "descripcion": "50x100m. Potencial para vivienda, complejos turísticos, locales comerciales o loteo. Zona de mayor crecimiento del valle.",
        "fotos_url": "https://esquelprop.com/propiedad/fraccion-de-5-000-m%c2%b2-en-la-entrada-a-trevelin/",
    },
    {
        "id": "EP022",
        "titulo": "1 Hectárea Los Cipreses, Trevelin",
        "precio_usd": "Consultar",
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Terreno",
        "ambientes": "",
        "dormitorios": "",
        "banos": "",
        "mt2_cubiertos": "",
        "mt2_totales": 10000,
        "barrio": "Ruta 259, Trevelin",
        "direccion": "Ruta 259, camino a la frontera, Trevelin",
        "cochera": "",
        "descripcion": "Sobre Ruta 259 en dirección a la frontera, proximidad al Río Blanco. Ideal proyectos turísticos rurales.",
        "fotos_url": "https://esquelprop.com/propiedad/1-hectarea-los-cipreses/",
    },
    {
        "id": "EP023",
        "titulo": "Fracción 1,5 has en Los Cipreses, Trevelin",
        "precio_usd": 41000,
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Terreno",
        "ambientes": "",
        "dormitorios": "",
        "banos": "",
        "mt2_cubiertos": "",
        "mt2_totales": 15000,
        "barrio": "Los Cipreses, Trevelin",
        "direccion": "Los Cipreses, Ruta 259, Trevelin",
        "cochera": "",
        "descripcion": "Terreno plano entre la ruta y el Río Grande. Cercado con alambre y tranquera. Luz eléctrica en la puerta. Curso de agua natural todo el año. Ideal viñedos o frutas finas.",
        "fotos_url": "https://esquelprop.com/propiedad/15-ha-con-agua-frente-a-psicultura/",
    },
    {
        "id": "EP024",
        "titulo": "Fracción 2,40 ha Esquel",
        "precio_usd": "Consultar",
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Terreno",
        "ambientes": "",
        "dormitorios": "",
        "banos": "",
        "mt2_cubiertos": "",
        "mt2_totales": 24000,
        "barrio": "Esquel",
        "direccion": "A 3 km del casco urbano, 100 m de Ruta 259, Esquel",
        "cochera": "",
        "descripcion": "2,40 hectáreas ideal inversores en urbanización o emprendimiento.",
        "fotos_url": "https://esquelprop.com/propiedad/fraccion-2-40-hectarea-esquel/",
    },
    {
        "id": "EP025",
        "titulo": "Fracciones de 3 ha Nido de Cóndores (Ruta 259)",
        "precio_usd": "Consultar",
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Terreno",
        "ambientes": "",
        "dormitorios": "",
        "banos": "",
        "mt2_cubiertos": "",
        "mt2_totales": 30000,
        "barrio": "Nido de Cóndores, Ruta 259",
        "direccion": "Ruta 259 entre Esquel y Trevelin",
        "cochera": "",
        "descripcion": "3 ha por fracción (150x200m). A 755 m de la Cooperativa 16. Se acepta permuta por vivienda en Esquel.",
        "fotos_url": "https://esquelprop.com/propiedad/fracciones-de-3-htas-nido-de-condores-ruta-259-esquel-trevelin/",
    },
    {
        "id": "EP026",
        "titulo": "3 ha en Cholila - Ruta Provincial N15",
        "precio_usd": 75000,
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Terreno",
        "ambientes": "",
        "dormitorios": "",
        "banos": "",
        "mt2_cubiertos": "",
        "mt2_totales": 30000,
        "barrio": "Cholila",
        "direccion": "Ruta Provincial N15, Cholila",
        "cochera": "",
        "descripcion": "Terreno plano, +70 m de frente sobre ruta, a 500 m del Lago Mosquito. Ideal viviendas o complejos turísticos.",
        "fotos_url": "https://esquelprop.com/propiedad/3-hta-en-cholila/",
    },
    {
        "id": "EP027",
        "titulo": "3 ha en venta Cholila, Chubut",
        "precio_usd": 93000,
        "tipo_operacion": "Venta",
        "tipo_propiedad": "Terreno",
        "ambientes": "",
        "dormitorios": "",
        "banos": "",
        "mt2_cubiertos": "",
        "mt2_totales": 30000,
        "barrio": "Cholila",
        "direccion": "Cholila, Chubut",
        "cochera": "",
        "descripcion": "A 200 m del asfalto, a metros de caminos principales. Accesible todo el año. USD 93.000 juntas o USD 35.000 por hectárea individual. Requiere mensura.",
        "fotos_url": "https://esquelprop.com/propiedad/3-hta-en-venta-cholila-chubut/",
    },
]

# --- Write to Google Sheet ---
sheet = gc.open_by_key(sheet_id)
ws = sheet.get_worksheet_by_id(567871247)
sheet_headers = ws.row_values(1)

existing_data = ws.get_all_values()
existing_ids = set()
if len(existing_data) > 1:
    id_col = sheet_headers.index("id")
    for row in existing_data[1:]:
        if row[id_col]:
            existing_ids.add(str(row[id_col]))

print(f"Sheet headers: {sheet_headers}")
print(f"Existing IDs in sheet: {len(existing_ids)}")

rows_to_add = []
for p in properties:
    if p["id"] in existing_ids:
        print(f"  Skip {p['id']} (already in sheet)")
        continue

    row = []
    for h in sheet_headers:
        val = p.get(h, "")
        row.append(val if val is not None else "")
    rows_to_add.append(row)

if rows_to_add:
    ws.append_rows(rows_to_add, value_input_option="USER_ENTERED")
    print(f"\nAdded {len(rows_to_add)} properties to sheet")
else:
    print("\nNo new properties to add")

print("DONE!")
